// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCORSw7TUs7Vo3dybfufTpUvkGUohWGMaI',
    appId: '1:185759031927:web:53d682bdbd67d14edddc72',
    messagingSenderId: '185759031927',
    projectId: 'musicplayerapp-fa3c1',
    authDomain: 'musicplayerapp-fa3c1.firebaseapp.com',
    storageBucket: 'musicplayerapp-fa3c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLU6_NiviBZJ1uLCvlTCY22an5HgN4NY',
    appId: '1:185759031927:android:20e9f424d584fcebdddc72',
    messagingSenderId: '185759031927',
    projectId: 'musicplayerapp-fa3c1',
    storageBucket: 'musicplayerapp-fa3c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdJFjoHftjpEK-yOi3z8C3-zlUvq32aY',
    appId: '1:185759031927:ios:ac2d40dc675ad090dddc72',
    messagingSenderId: '185759031927',
    projectId: 'musicplayerapp-fa3c1',
    storageBucket: 'musicplayerapp-fa3c1.appspot.com',
    iosBundleId: 'com.example.musicplayerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZdJFjoHftjpEK-yOi3z8C3-zlUvq32aY',
    appId: '1:185759031927:ios:6b6d4713118e2bfedddc72',
    messagingSenderId: '185759031927',
    projectId: 'musicplayerapp-fa3c1',
    storageBucket: 'musicplayerapp-fa3c1.appspot.com',
    iosBundleId: 'com.example.musicplayerapp.RunnerTests',
  );
}
